Adding missing virtual destructors
error: 'dtn::storage::DataStorage::Callback' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor].
error: 'dtn::daemon::Configuration::Extension' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]
error: 'dtn::daemon::Configuration::OnChangeListener' has virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor]